#application.yml or application.properties used to bind external properties into an application at runtime

twitter-to-kafka-service:
  twitterKeywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcomeMessage : Hello There
  enable-v2-tweets: false
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 1000
  twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
  twitter-v2-rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
  twitter-v2-bearer-token: ${TWITTER_BEARER_TOKEN}

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy #snappy compression arranges compression ratio for higher compress/decompress speed
  acks: all # all - wait ack from all replicas, 1 - wait only current broker's ack, 0 - no ack
  batch-size: 16384 #16kb
  batch-size-boost-factor: 100 #tune for higher throughput
  linger-ms: 5 #add a delay on producer in case of light load
  request-timeout-ms: 60000 #6s
  retry-count: 5 #retry 5 times when error